require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TransitionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Transition. As you add validations to Transition, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TransitionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all transitions as @transitions" do
      transition = Transition.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:transitions)).to eq([transition])
    end
  end

  describe "GET #show" do
    it "assigns the requested transition as @transition" do
      transition = Transition.create! valid_attributes
      get :show, params: {id: transition.to_param}, session: valid_session
      expect(assigns(:transition)).to eq(transition)
    end
  end

  describe "GET #new" do
    it "assigns a new transition as @transition" do
      get :new, params: {}, session: valid_session
      expect(assigns(:transition)).to be_a_new(Transition)
    end
  end

  describe "GET #edit" do
    it "assigns the requested transition as @transition" do
      transition = Transition.create! valid_attributes
      get :edit, params: {id: transition.to_param}, session: valid_session
      expect(assigns(:transition)).to eq(transition)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Transition" do
        expect {
          post :create, params: {transition: valid_attributes}, session: valid_session
        }.to change(Transition, :count).by(1)
      end

      it "assigns a newly created transition as @transition" do
        post :create, params: {transition: valid_attributes}, session: valid_session
        expect(assigns(:transition)).to be_a(Transition)
        expect(assigns(:transition)).to be_persisted
      end

      it "redirects to the created transition" do
        post :create, params: {transition: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Transition.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved transition as @transition" do
        post :create, params: {transition: invalid_attributes}, session: valid_session
        expect(assigns(:transition)).to be_a_new(Transition)
      end

      it "re-renders the 'new' template" do
        post :create, params: {transition: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested transition" do
        transition = Transition.create! valid_attributes
        put :update, params: {id: transition.to_param, transition: new_attributes}, session: valid_session
        transition.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested transition as @transition" do
        transition = Transition.create! valid_attributes
        put :update, params: {id: transition.to_param, transition: valid_attributes}, session: valid_session
        expect(assigns(:transition)).to eq(transition)
      end

      it "redirects to the transition" do
        transition = Transition.create! valid_attributes
        put :update, params: {id: transition.to_param, transition: valid_attributes}, session: valid_session
        expect(response).to redirect_to(transition)
      end
    end

    context "with invalid params" do
      it "assigns the transition as @transition" do
        transition = Transition.create! valid_attributes
        put :update, params: {id: transition.to_param, transition: invalid_attributes}, session: valid_session
        expect(assigns(:transition)).to eq(transition)
      end

      it "re-renders the 'edit' template" do
        transition = Transition.create! valid_attributes
        put :update, params: {id: transition.to_param, transition: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested transition" do
      transition = Transition.create! valid_attributes
      expect {
        delete :destroy, params: {id: transition.to_param}, session: valid_session
      }.to change(Transition, :count).by(-1)
    end

    it "redirects to the transitions list" do
      transition = Transition.create! valid_attributes
      delete :destroy, params: {id: transition.to_param}, session: valid_session
      expect(response).to redirect_to(transitions_url)
    end
  end

end
